### ISSUE TITLE
03-07-2018 Pasta Dinner meeting

### ISSUE THREAD

**Issue by keywordnew** [cambiecollective/cambiecollective.github.io#10]
## Time

**PST 03-Jul-2018 18:30 (06:30 PM)**

## Links

* Minutes Google Doc: <https://docs.google.com/document/d/15aI41KfzHIrNNJEZ2m3SUPFs63Q69gkTu8fQmHl0pto/edit>

## Agenda

Extracted from **gg-agenda** labelled issues and pull requests from the **gastowngang org** prior to the meeting.

To add an agenda item, please open an issue.

### gastowngang/gastowngang.github.io

* Document the benefits of a non-profit org to meetups [#6](https://github.com/gastowngang/gastowngang.github.io/issues/6)

* Gastown Gang can curate a public calendar of meetups [#7](https://github.com/gastowngang/gastowngang.github.io/issues/7)

* requirements for participation [#11](https://github.com/gastowngang/gastowngang.github.io/issues/11)

## Invited

* @Mariatta 
* @Qard 
* @expede
* @chowdhurian
* @daffl
* @caffodian 

This list is being updated.

## Notes

The agenda comes from issues labelled with `gg-agenda` across **all of the repositories in the gastowngang org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

The meeting will be held in-person at The Old Spaghetti Factory in Gastown.

**Comment by Mariatta** [comment]
Alternative names:
- Gastown Alliance
- Gastown Squad
- Gastown Crew

I like the "Gastown" element, I think we should keep it :)

**Comment by caffodian** [comment]
Obviously terrible alliteration:

Gastown Group
Gastown Gathering

One thing I like about Stumptown Syndicate (now that i look at the site) is that there's a pretty clear mission statement in the tagline (though they seem to have two different taglines)

**Comment by caffodian** [comment]
spun off #12 for figuring out what info we want to capture about venues - though if anyone has any immediate need for venues etc. talk to me and I'll see what I can share

**Comment by Qard** [comment]
Granville Group flows a little better than Gastown Group, I think. Though I like the brick-and-mortar image the “Gastown” name projects. 🤔

Should we consider distancing from regional naming though, in case this grows beyond just serving Vancouver?

**Comment by caffodian** [comment]
> Granville Group flows a little better than Gastown Group, I think. Though I like the brick-and-mortar image the “Gastown” name projects. 🤔

I think Granville (Entertainment) Group owns the Roxy, lol

**Comment by Qard** [comment]
Maybe we can steal their name and get free use of The Roxy as a venue. :trollface:

**Comment by caffodian** [comment]
crossposted to #6 but https://guides.vpl.ca/c.php?g=698584&p=4971947 is a wealth of nonprofit resources 

http://www.strategis.gc.ca/eic/site/cd-dgc.nsf/frm-eng/NGRR-8AFNVX is a bylaw builder tool that seems useful, though we probably should get actual legal advice

**Comment by keywordnew** [comment]
This bylaw builder is gold. This is what civic tech is meant for! 💯

**Comment by keywordnew** [comment]
The next Pasta Dinner is at #20. Closing this now.

Please feel free to reopen if you want!
