### ISSUE TITLE
The page's content needs to be updated with the new name

### ISSUE THREAD

**Issue by keywordnew** [cambiecollective/cambiecollective.github.io#26]
Related to #14. Now that the name has been changed, the mentions of Gastown Gang on the website needs to be updated with Cambie Collective.

This is a good first issue! Happy to help out and provide context for any person taking this on!

**Comment by uncojohnco** [comment]
hi @chowdhurian  - I can have a look at this...

Context:
I attended a meeting last week to reignite [VanPy meetups](https://www.meetup.com/vanpyz). @caffodian mentioned that this group had rebranded, and I'm learning full-stack web development, so I thought I can use this as a learning opportunity :)

**Comment by uncojohnco** [comment]
hi @chowdhurian - should I close #27 as it looks like your latest commits look to have resolved this issue? :)

**Comment by keywordnew** [comment]
@oikake I took a look at the timestamp, your commits were made earlier than my latest changes. I made those without checking the repo. The mistake was mine!

I've reverted the changes I made. I reviewed #27.
