### ISSUE TITLE
Design a Cambie Collective logo

### ISSUE THREAD

**Issue by apike** [cambiecollective/cambiecollective.github.io#31]
Cambie Collective has a [relatively nice web page](https://cambiecollective.github.io/) but arguably doesn't have a logo yet (the placeholder being used right now is a screenshot of an Open Street Map of Gastown). I think investing a bit of Steamclock's time here to design logos for CC and VanJS would could be a worthwhile contribution to the community.

A potential brief for the Cambie Collective logo would be:

- Target audience: Developers and other creative tech people in Vancouver. People who might be motivated to attend or help organize inclusive, community-minded tech events in town.
- Potential themes: Community, inclusion, building, Vancouver, development, Gastown, meetups.
- Usage: Primarily as an avatar, so a logo that fits well in a circle is ideal.

Any objections to the above, or goals/ideas we should have in mind when thinking about a Cambie Collective logo?

**Comment by keywordnew** [comment]
Logos/symbols help humans to identify with shared goals. I for one appreciate Steamclock's willingness to initiate a contribution of this nature 💛

The potential brief LGTM 🙌🏽 My top three themes would be inclusion, Vancouver/Gastown (fudging by mashing the regions together), and creative technology.

+1 on a logo that fits well in a circle, and looks good as a sticker.

And that follows some [principles of flag design](https://www.youtube.com/watch?v=pnv5iKB2hl4) 👉🏽 Feel free to tell me I'm getting carried away.

**Comment by apike** [comment]
Ha, great! But maybe let's stick with the principles of logo design for now, and then loop back to the principles of flag design if we end up doing a flag variation. 😁

**Comment by Qard** [comment]
If we can, it'd be nice to be able to somehow communicate the empowerment factor, enabling the community to help drive things.

**Comment by Mariatta** [comment]
All sounds good to me! Thank you @apike & Steamclock!

**Comment by apike** [comment]
At long last, we have something to show and collect feedback on this! Some goals we had:

- Feel friendly and inclusive
- Convey that this is a community/indie organization
- Offer an avatar-shaped image as well as a wordmark
- Be clean and crisp enough to fit as a tech/creative brand

Our awesome designer/illustrator Erica started with a sketch that we quite liked:

![image](https://user-images.githubusercontent.com/129240/61653701-bd5f5680-ac6f-11e9-83b6-88c8137a7ea3.png)

We have a couple colour combinations that might work well for this: one with a green that might be a bit more Vancouver-y, and one with a purple that might be more distinctive and echo the purple on the current Cambie Collective site.

![image](https://user-images.githubusercontent.com/129240/61649465-6608b880-ac66-11e9-99a4-bdca335f65a1.png)

Any thoughts on these two options and whether this is a reasonable approach for the group?

**Comment by keywordnew** [comment]
Wow, Erica, this is SO very wonderful! 

Thank you for the update Allen!

- [x] Feel friendly and inclusive
- [x] Convey that this is a community/indie organization
- [x] Offer an avatar-shaped image as well as a wordmark
- [x] Be clean and crisp enough to fit as a tech/creative brand

All the boxes checked, imo! They both have merits that I'm actually finding it difficult to choose between the two. I do like how the purple echoes the purple on the current site, although having that pro stand on its own is risky since the site could change. I think the teal is also quite distinctive but might be more difficult to read in certain conditions, which are maybe less relevant if these will always be rendered digitally.

Maybe more discussion on this thread would help me too :p

**Comment by Qard** [comment]
Nice! I like it. :)

That M also somewhat evokes the Epic Handshake meme for me. 😆 

![epic handshake](https://i.imgflip.com/ya268.jpg)

**Comment by keywordnew** [comment]
Polled more folks on the proposed candidates. Including the feedback in points:

* The reddish-orange of the one on top versus the more yellowish-orange of the bottom is generally liked.
* It was pointed out that the wordmark with the green might not test well for red-green colorblindedness and so may pose an accessibility issue. 
* I loved the way the loop disconnects on the fancy "m". The closure makes for a great effect. I'm not clued in on why "m" was chosen as our letter but I like it all the same!
* Friendly vibes reported all around.

**Comment by apike** [comment]
We definitely do want to be thoughtful of colourblindness for the orange/green logo, but based on simulated colourblindness filters it seems the two colours are still visually distinct in that case so I think we're good there. If that's the more popular combo otherwise, shall we prep and hand over vector versions of that scheme?

**Comment by keywordnew** [comment]
^ Sounds good to me!

Our next steps would be:
- [x] To update the logo on the site. Good first issue right there.
- [x] Update on Github org and Twitter
- [x] Update Slack
- [ ] ?

**Comment by ehyleong** [comment]
Hi! Here are the final assets for the avatar and wordmark in .PNG, .AI and .PDF! 🎉In addition:
- I included square and circle versions of the avatar
- I added a white variant of the wordmark (in case it's being used on a dark or coloured background)

Any changes can be made to the vector file (.AI) -- but do let us know if you need anything else! 

[Cambie Collective.zip](https://github.com/cambiecollective/cambiecollective.github.io/files/3494311/Cambie.Collective.zip)

**Comment by keywordnew** [comment]
Updated Twitter, Github, and Slack with new avatar.

Created issue #35 to update the site.
