### ISSUE TITLE
NodeJS and other non-frontend JavaScript meetup

### ISSUE THREAD

**Issue by daffl** [cambiecollective/cambiecollective.github.io#8]
As briefly mentioned to @chowdhurian last weekend, I'd be interested in hosting a more regular Vancouver meetup focussed on NodeJS and other uses of JavaScript outside of web frontends technologies.

__What I can offer__

- From 2012 to 2016 I helped start and run YYCJS, the Calgary JavaScript meetup ([Meetup](https://www.meetup.com/yyc-js/), [GitHub](https://github.com/yycjs), [YouTube](https://www.youtube.com/user/yycjs)). It grew to one of the largest technology meetups in Alberta with now over 800 members.
- We learned many things about running a meetup (presentation format, recording, promotion, collaborating with other groups) during that time that I would be happy to put to use again
- There is a lot of material from talks I gave at that time that could be used again
- The first event could be (co)sponsored by the [Feathers OpenCollective](https://opencollective.com/feathers) if it features a talk about [FeathersJS](https://feathersjs.com/) and is being recorded

__What I'd be looking for__

- Help with securing a suitable venue
- Help with promoting the event
- A co-host to share some of the workload
- Depending on size possibly volunteers (?)
- Speakers (for future events)

As a timeframe I would be looking at some time in May or June for the first event.

**Comment by keywordnew** [comment]
> Help with promoting the event

Current meetups (NodeSchoolYVR and Code & Coffee) can promote the event in the weeks leading up to it.

> A co-host to share some of the workload

Can put out a call for co-hosts on Twitter and Github channels.

> Depending on size possibly volunteers (?)

If it's like the Code and Coffee format, the comfort ratio is 1 organizer for every 25 attendees. That's an event with an established routine and it won't take long to get to that point, especially with prior organizing experience on board.

> Speakers (for future events)

We could start keeping a record of past speakers to help with this. Worth spending more time thinking about.

**Comment by Qard** [comment]
I can definitely help with promoting, volunteering and organizing things. I'm happy to speak at some point too. 👍

I could also reach out to @sintaxi to see if perhaps we can send a message out to the mailing list for the long-dormant [Node Brigade](https://www.meetup.com/node-brigade-vancouver/), when we have something more solid to talk about.

**Comment by sintaxi** [comment]
Yes! definitely. Just let me know.

**Comment by daffl** [comment]
Awesome, thanks everyone! @chowdhurian, @Qard would you be open to discussing the next steps over beverages some time next week? Some of the questions I have would be:

- Should I create a separate meetup group (name TBA) or were you thinking of having a Gastowngang group hosting the different meetups?
- What options would there be for venues holding 50 to 100 people for the second half of May or early June?
- Potential cost and additional sponsors?

**Comment by Qard** [comment]
I’m of the opinion that each event should have its own identity. Gastown Gang would mainly just be a support organization.

I’m happy to get drinks sometime. Maybe we can make arrangements in Slack at some point, so as not to clutter up this issue?

For sponsorship, I can talk to Elastic and see if I can get something from them. We should have a clearer idea of what that gives them though.

**Comment by keywordnew** [comment]
+1 to separate identities. The intended purpose of Gastown Gang is for support, and getting started.

+1 to discussing next steps in-person, and planning in chat.

> Should I create a separate meetup group (name TBA) or were you thinking of having a Gastowngang group hosting the different meetups?

We could discuss meetup subscriptions. I believe pricing can be batched but they would be operated independently.

> What options would there be for venues holding 50 to 100 people for the second half of May or early June?

Two come to mind: the Central Library, and Telus. This is the [pricing chart](https://www.vpl.ca/rooms/reservations.html#nonprofit) for the library. We'd need help with Telus.

> We should have a clearer idea of what that gives them though.

I do still need to work on #9, which could address this. Sorry for the holdup! 🙏🏽 There have been some tasks that took over the week.

**Comment by daffl** [comment]
Thanks again for meeting up on Friday. Here's a quick summary (from what I remember 😉):

- Meetup to be held under the Nodeschool umbrella. Is there a Nodeschool meetup account? I [did a search](https://www.meetup.com/find/events/?allMeetups=false&keywords=nodeschool&radius=50&userFreeform=Vancouver%2C+BC&mcId=z862498&mcName=Vancouver%2C+British+Columbia%2C+CA&eventFilter=mysugg) but couldn't find anything
- Name still TBA - "Nodeschool ___" (_connect_, _meets_) - suggestions welcome
- Tentative date for first event: June 19th (and every third Tuesday every other month thereafter)
- First meetup can be sponsored by the [FeathersJS OpenCollective](https://www.vpl.ca/rooms/reservations.html#nonprofit) (as long as it features a Feathers related talk and it is being recorded)
- Location at [Library Square](https://www.vpl.ca/rooms/reservations.html#nonprofit) booked through the non-profit Code & Coffee (featured as a sponsor)
- @chowdhurian will look at the rooms and rates and we'll follow up from there
- Also need to find out what the audio setup there is like and if it has everything required to record the event

Let me know if I forgot anything

**Comment by Qard** [comment]
https://www.meetup.com/nodeschool-vancouver/

**Comment by keywordnew** [comment]
Throwing it out there for consideration: what would the advantages be of having this after the NodeSchool workshoppers on Saturdays? Red Academy may have space for us, if they'd be ok with doing it in the evening.

**Comment by Qard** [comment]
I'd definitely be cool with doing them on the same day, if the venue can support it. 👍

**Comment by daffl** [comment]
That would make sense, as long as it isn't too late (5ish?) and there is enough capacity (what's the seating for Red Academy?)?

**Comment by keywordnew** [comment]
If done after the usual Saturday workshop session it would have to be 5 or later. Otherwise it would cut into the first session, which we def don't want to do.

About 20. I believe the seating changes by the space we would have assigned. The number is lower than I had expected.

**Comment by keywordnew** [comment]
The Node&JS Community Hangouts could fill the community gap outlined in the original comment. Also the possibility of VanJS becoming more active will help with this!

**Comment by keywordnew** [comment]
Closing this issue for now. Please feel free to reopen if at all necessary! 💜
